name: flutter_demo
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: 1.2.0
  bloc: ^6.0.3
  flutter_bloc: ^6.0.5
  cloud_firestore: 0.14.1+3
  firebase_core: 0.5.0+1
  bloc_test: 7.0.2
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
